# Generated by Django 5.2.7 on 2026-02-11 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='delivery_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='prescription',
            field=models.ImageField(blank=True, null=True, upload_to='prescriptions/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('syrup', 'Syrup'), ('ointment', 'Ointment'), ('equipment', 'Equipment'), ('kit', 'Kit'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='prescription_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='login',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('pharmacy', 'Pharmacy'), ('user', 'User'), ('delivery', 'Delivery Boy')], max_length=10),
        ),
        migrations.CreateModel(
            name='DeliveryBoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(default='active', max_length=20)),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pharmacy')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.deliveryboy'),
        ),
    ]
