# Generated by Django 5.2.7 on 2026-02-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('picked_up', 'Picked Up'), ('on_the_way', 'On the Way'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
