# Generated by Django 5.2.7 on 2026-02-22 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_booking_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.booking'),
        ),
    ]
